package thicket.renderer.apple

import scala.scalanative.unsafe.*

/** Bindings for `shim/include/thicket_apple.h`.
  *
  * GENERATED by tools/shim-gen from thicket.tools.shim.Abi. Do not edit by hand: edit
  * Abi.scala and run `sbt shimGen/run`. `sbt shimGen/test` fails while this file and Abi
  * disagree.
  *
  * Every signature is scalars or out-parameters: no struct crosses this boundary by value,
  * because Scala Native gets that silently wrong on both x86-64 and arm64 (S4, S3).
  */
@extern
object Shim {

  type Handle = Ptr[Byte]
  type VoidCb = CFuncPtr1[Long, Unit]
  type TextCb = CFuncPtr2[Long, CString, Unit]
  type BoolCb = CFuncPtr2[Long, CInt, Unit]

  /** The only callback that returns a value. A returned pointer is one register; what S4 and S3 found silently broken
    * was a returned small struct.
    */
  type RowCb = CFuncPtr3[Long, CInt, Handle, Handle]

  /** A slider's value, in the app's own units. */
  type ValueCb = CFuncPtr2[Long, Double, Unit]

  /** A small integer, such as the depth a navigation stack was popped to. */
  type IntCb = CFuncPtr2[Long, CInt, Unit]

  def sui_app_start(width: CInt, height: CInt, title: CString, ready: VoidCb, ctx: Long): Unit = extern
  def sui_root_view(): Handle = extern
  def sui_window_set_title(title: CString): Unit = extern
  def sui_create(kind: CInt): Handle = extern
  def sui_destroy(h: Handle): Unit = extern
  def sui_set_text(h: Handle, text: CString): Unit = extern
  def sui_set_placeholder(h: Handle, text: CString): Unit = extern
  def sui_set_checked(h: Handle, on: CInt): Unit = extern
  def sui_get_checked(h: Handle): CInt = extern
  def sui_set_enabled(h: Handle, on: CInt): Unit = extern
  def sui_set_spacing(h: Handle, dp: CInt): Unit = extern
  def sui_set_padding(h: Handle, dp: CInt): Unit = extern
  def sui_set_text_role(h: Handle, role: CInt): Unit = extern
  def sui_set_text_emphasis(h: Handle, emphasis: CInt): Unit = extern
  def sui_set_grow(h: Handle, on: CInt): Unit = extern
  def sui_set_align(h: Handle, align: CInt): Unit = extern
  def sui_set_tint(h: Handle, has: CInt, r: CInt, g: CInt, b: CInt): Unit = extern
  def sui_set_fill(h: Handle, has: CInt, r: CInt, g: CInt, b: CInt): Unit = extern
  def sui_set_image_file(h: Handle, path: CString): Unit = extern
  def sui_set_image_bytes(h: Handle, data: Ptr[Byte], length: CInt): Unit = extern
  def sui_clear_image(h: Handle): Unit = extern
  def sui_set_content_fit(h: Handle, fit: CInt): Unit = extern
  def sui_set_progress(h: Handle, has: CInt, fraction: CDouble): Unit = extern
  def sui_set_range(h: Handle, min: CDouble, max: CDouble): Unit = extern
  def sui_set_value(h: Handle, value: CDouble): Unit = extern
  def sui_on_tap(h: Handle, cb: VoidCb, ctx: Long): Unit = extern
  def sui_on_text_change(h: Handle, cb: TextCb, ctx: Long): Unit = extern
  def sui_on_checked_change(h: Handle, cb: BoolCb, ctx: Long): Unit = extern
  def sui_on_value_change(h: Handle, cb: ValueCb, ctx: Long): Unit = extern
  def sui_insert_after(parent: Handle, child: Handle, after: Handle): Unit = extern
  def sui_remove_child(parent: Handle, child: Handle): Unit = extern
  def sui_measure(h: Handle, maxW: CDouble, maxH: CDouble, outMinW: Ptr[CDouble], outMinH: Ptr[CDouble], outNatW: Ptr[CDouble], outNatH: Ptr[CDouble]): Unit = extern
  def sui_set_frame(h: Handle, x: CDouble, y: CDouble, w: CDouble, height: CDouble): Unit = extern
  def sui_run_on_main(cb: VoidCb, ctx: Long): Unit = extern
  def sui_run_on_main_after(delay_ms: CInt, cb: VoidCb, ctx: Long): Unit = extern
  def sui_create_table(cb: RowCb, ctx: Long): Handle = extern
  def sui_table_reload(h: Handle, count: CInt): Unit = extern
  def sui_table_materialised(h: Handle): CInt = extern
  def sui_table_live(): CInt = extern
  def sui_present(h: Handle): Unit = extern
  def sui_dismiss(h: Handle): Unit = extern
  def sui_set_message(h: Handle, text: CString): Unit = extern
  def sui_alert_clear_actions(h: Handle): Unit = extern
  def sui_alert_add_action(h: Handle, label: CString, role: CInt, cb: VoidCb, ctx: Long): Unit = extern
  def sui_on_dismiss(h: Handle, cb: VoidCb, ctx: Long): Unit = extern
  def sui_menu_clear(h: Handle): Unit = extern
  def sui_menu_add_item(h: Handle, label: CString, enabled: CInt, cb: VoidCb, ctx: Long): Unit = extern
  def sui_picker_clear_options(h: Handle): Unit = extern
  def sui_picker_add_option(h: Handle, label: CString): Unit = extern
  def sui_set_selected(h: Handle, index: CInt): Unit = extern
  def sui_get_selected(h: Handle): CInt = extern
  def sui_on_select(h: Handle, cb: IntCb, ctx: Long): Unit = extern
  def sui_pages_begin(): Unit = extern
  def sui_pages_add(id: Long, content: Handle, title: CString): Unit = extern
  def sui_pages_commit(): Unit = extern
  def sui_on_pages_popped(cb: IntCb, ctx: Long): Unit = extern
  def sui_child_count(h: Handle): CInt = extern
  def sui_child_at(h: Handle, index: CInt): Handle = extern
  def sui_get_text(h: Handle): CString = extern
  def sui_is_text_bearing(h: Handle): CInt = extern
  def sui_class_name(h: Handle): CString = extern
  def sui_get_progress(h: Handle): CDouble = extern
  def sui_get_value(h: Handle): CDouble = extern
  def sui_is_secure(h: Handle): CInt = extern
  def sui_has_image(h: Handle): CInt = extern
  def sui_scroll_offset(h: Handle): CDouble = extern
  def sui_is_presented(h: Handle): CInt = extern
  def sui_presented_title(h: Handle): CString = extern
  def sui_presented_message(h: Handle): CString = extern
  def sui_menu_item_count(h: Handle): CInt = extern
  def sui_menu_item_label(h: Handle, index: CInt): CString = extern
  def sui_pages_depth(): CInt = extern
  def sui_page_title(index: CInt): CString = extern
  def sui_pages_shown(): CInt = extern
  def sui_pages_back_offered(): CInt = extern
  def sui_pages_back(): CInt = extern
  def sui_menu_live(): CInt = extern
  def sui_menu_activate(h: Handle, index: CInt): CInt = extern
  def sui_presented_count(): CInt = extern
  def sui_alert_action_count(h: Handle): CInt = extern
  def sui_alert_action_label(h: Handle, index: CInt): CString = extern
  def sui_perform_click(h: Handle): CInt = extern
  def sui_alert_choose(h: Handle, index: CInt): CInt = extern
}

/** `sui_create` kind codes, from Abi.kinds. A code whose view is "-" on a toolkit is
  * reserved and not built there; see the table in `thicket_apple.h`.
  */
object ShimKind {
  inline val Column = 0
  inline val Row = 1
  inline val Label = 2
  inline val Button = 3
  inline val TextField = 4
  inline val Checkbox = 5
  inline val Scroll = 6
  inline val Divider = 7
  inline val Image = 8
  inline val Toggle = 9
  inline val Spacer = 10
  inline val ProgressBar = 11
  inline val ActivityIndicator = 12
  inline val Slider = 13
  inline val SecureField = 14
  inline val ScrollHorizontal = 15
  inline val Alert = 16
  inline val Sheet = 17
  inline val Picker = 18
}
