/*
 * The Scala <-> Apple contract.
 *
 * GENERATED by tools/shim-gen from thicket.tools.shim.Abi. Do not edit by hand: edit
 * tools/shim-gen/src/main/scala/thicket/tools/shim/Abi.scala and run `sbt shimGen/run`.
 * `sbt shimGen/test` fails while this file and Abi disagree, because otherwise the Scala
 * bindings and the two Swift shims drift from it and nothing says so until a callback
 * reads the wrong register.
 *
 * NO STRUCTS BY VALUE anywhere a Scala callback is involved, and none returned across the
 * boundary either: S4 found Scala Native returns a small struct from a CFuncPtr in the
 * wrong registers, silently, and S3 confirmed it still does on arm64 with a *different*
 * wrong answer. NSRect/NSSize are pervasive in AppKit, so everything here is flattened to
 * scalars or out-parameters.
 */
#ifndef THICKET_APPLE_H
#define THICKET_APPLE_H

#include <stdint.h>

#include "thicket_apple_types.h"

/* --- lifecycle --------------------------------------------------------------- */
void sui_app_start(int32_t width, int32_t height, const char *title,
                   sui_void_cb ready, int64_t ctx);
sui_handle sui_root_view(void);
void sui_window_set_title(const char *title);

/* --- widget construction ----------------------------------------------------- */
/* kind: the view each toolkit builds. A different *widget* per platform is chosen here,
   not only a different name. Generated from Abi.kinds; ConsistencySpec checks both
   shims' sui_create build what this says.

      0 Column             TapView()                      UIStackView()
      1 Row                TapView()                      UIStackView()
      2 Label              NSTextField(labelWithString:)  UILabel()         AppKit has no label class
      3 Button             NSButton(title:)               UIButton(type:)
      4 TextField          NSTextField(string:)           UITextField()
      5 Checkbox           NSButton(checkboxWithTitle:)   UISwitch()        UIKit has no checkbox
      6 Scroll             NSScrollView()                 UIScrollView()    vertical
      7 Divider            NSBox()                        UIView()          the shims' default: branch
      8 Image              ImageView()                    UIImageView()
      9 Toggle             NSSwitch()                     UISwitch()        no label: the caption is a sibling
     10 Spacer             NSView()                       UIView()          grows through Prop.Grow
     11 ProgressBar        NSProgressIndicator()          UIProgressView()
     12 ActivityIndicator  NSProgressIndicator()          UIActivityIndicatorView()  spins while mounted
     13 Slider             NSSlider()                     UISlider()
     14 SecureField        NSSecureTextField()            UITextField()     isSecureTextEntry on UIKit
     15 ScrollHorizontal   NSScrollView()                 UIScrollView()    the axis is read at create
     16 Alert              -                              -                 reserved, not built yet (phase 3; NSAlert / UIAlertController) */
sui_handle sui_create(int32_t kind);
void sui_destroy(sui_handle h);

/* --- properties -------------------------------------------------------------- */
void sui_set_text(sui_handle h, const char *text);
void sui_set_placeholder(sui_handle h, const char *text);
void sui_set_checked(sui_handle h, int32_t on);
int32_t sui_get_checked(sui_handle h);
void sui_set_enabled(sui_handle h, int32_t on);
void sui_set_spacing(sui_handle h, int32_t dp);
void sui_set_padding(sui_handle h, int32_t dp);
/* role: 0 Title, 1 Body, 2 Caption */
void sui_set_text_role(sui_handle h, int32_t role);
/* emphasis: 0 Normal, 1 Secondary */
void sui_set_text_emphasis(sui_handle h, int32_t emphasis);
void sui_set_grow(sui_handle h, int32_t on);
/* align: 0 Start, 1 Center, 2 End */
void sui_set_align(sui_handle h, int32_t align);
/* Colour is passed as three components plus a "set" flag rather than a struct:
   `None` means "leave it to the platform", which is not the same as black. */
void sui_set_tint(sui_handle h, int32_t has, int32_t r, int32_t g, int32_t b);
void sui_set_fill(sui_handle h, int32_t has, int32_t r, int32_t g, int32_t b);
void sui_set_image_file(sui_handle h, const char *path);
void sui_set_image_bytes(sui_handle h, const uint8_t *data, int32_t length);
void sui_clear_image(sui_handle h);
/* fit: 0 Contain, 1 Cover, 2 Fill */
void sui_set_content_fit(sui_handle h, int32_t fit);
/* has 0 means indeterminate, which is deliberately not the same as a fraction of 0.0.
   The fraction is 0.0-1.0; the shim scales it for NSProgressIndicator's 0-100. */
void sui_set_progress(sui_handle h, int32_t has, double fraction);
/* A slider's bounds, in the app's own units. Always arrives before sui_set_value. */
void sui_set_range(sui_handle h, double min, double max);
/* A slider's value, in the app's own units. Written only when it differs, so an
   app writing back what the user dragged to does not fight the drag. */
void sui_set_value(sui_handle h, double value);

/* --- events ------------------------------------------------------------------ */
void sui_on_tap(sui_handle h, sui_void_cb cb, int64_t ctx);
void sui_on_text_change(sui_handle h, sui_text_cb cb, int64_t ctx);
void sui_on_checked_change(sui_handle h, sui_bool_cb cb, int64_t ctx);
void sui_on_value_change(sui_handle h, sui_value_cb cb, int64_t ctx);

/* --- tree -------------------------------------------------------------------- */
void sui_insert_after(sui_handle parent, sui_handle child, sui_handle after);
void sui_remove_child(sui_handle parent, sui_handle child);

/* --- layout ------------------------------------------------------------------ */
/* Out-parameters, not a returned NSSize: see the header comment. maxW/maxH are
   NaN for "unconstrained", matching Constraints. */
void sui_measure(sui_handle h, double maxW, double maxH, double *outMinW,
                 double *outMinH, double *outNatW, double *outNatH);
void sui_set_frame(sui_handle h, double x, double y, double w, double height);

/* --- threading --------------------------------------------------------------- */
void sui_run_on_main(sui_void_cb cb, int64_t ctx);

/* --- virtual rows ------------------------------------------------------------ */
/* The one place control is inverted: everywhere else Scala builds a tree and the shim
   obeys, but a table asks for the row it is about to show and recycles the ones it is not. */
/* An NSTableView / UITableView inside its scroller. `cb` is called for each row
   that becomes visible, with a recycled view or NULL. */
sui_handle sui_create_table(sui_row_cb cb, int64_t ctx);
/* The new row count, from RowSource.onInvalidate. */
void sui_table_reload(sui_handle h, int32_t count);
/* How many row views the table has actually created. The measurement that says
   virtualisation is working, so it is part of the ABI rather than the self-test. */
int32_t sui_table_materialised(sui_handle h);
/* How many table sources the shim still owns. Falls back to zero once every
   virtual list is destroyed; the measurement that says destroying one frees it. */
int32_t sui_table_live(void);

/* --- inspection, for the self-test ------------------------------------------- */
int32_t sui_child_count(sui_handle h);
sui_handle sui_child_at(sui_handle h, int32_t index);
/* Returns NULL when the view carries no text. The buffer is owned by the shim and
   valid until the next call, so Scala must copy before calling again. */
const char *sui_get_text(sui_handle h);
int32_t sui_is_text_bearing(sui_handle h);
/* The platform class of the view, e.g. NSSwitch. What the platform built, not what
   the renderer asked for. Same buffer rule as sui_get_text. */
const char *sui_class_name(sui_handle h);
/* A determinate fraction 0.0-1.0; -1 when indeterminate (a spinner, or a bar given
   no fraction); -2 when the view shows no progress at all. */
double sui_get_progress(sui_handle h);
/* A slider's value, in the app's own units. */
double sui_get_value(sui_handle h);
/* 1 when the field masks what is typed into it. */
int32_t sui_is_secure(sui_handle h);

#endif
