/*
 * The Scala <-> Apple contract.
 *
 * GENERATED by tools/shim-gen from thicket.tools.shim.Abi. Do not edit by hand: edit
 * tools/shim-gen/src/main/scala/thicket/tools/shim/Abi.scala and run `sbt shimGen/run`.
 * `sbt shimGen/test` fails while this file and Abi disagree, because otherwise the Scala
 * bindings and the two Swift shims drift from it and nothing says so until a callback
 * reads the wrong register.
 *
 * NO STRUCTS BY VALUE anywhere a Scala callback is involved, and none returned across the
 * boundary either: S4 found Scala Native returns a small struct from a CFuncPtr in the
 * wrong registers, silently, and S3 confirmed it still does on arm64 with a *different*
 * wrong answer. NSRect/NSSize are pervasive in AppKit, so everything here is flattened to
 * scalars or out-parameters.
 */
#ifndef THICKET_APPLE_H
#define THICKET_APPLE_H

#include <stdint.h>

#include "thicket_apple_types.h"

/* --- lifecycle --------------------------------------------------------------- */
void sui_app_start(int32_t width, int32_t height, const char *title,
                   sui_void_cb ready, int64_t ctx);
sui_handle sui_root_view(void);
void sui_window_set_title(const char *title);

/* --- widget construction ----------------------------------------------------- */
/* kind: the view each toolkit builds. A different *widget* per platform is chosen here,
   not only a different name. Generated from Abi.kinds; ConsistencySpec checks both
   shims' sui_create build what this says.

      0 Column             TapView()                      UIStackView()
      1 Row                TapView()                      UIStackView()
      2 Label              NSTextField(labelWithString:)  UILabel()         AppKit has no label class
      3 Button             NSButton(title:)               UIButton(type:)
      4 TextField          NSTextField(string:)           UITextField()
      5 Checkbox           NSButton(checkboxWithTitle:)   UISwitch()        UIKit has no checkbox
      6 Scroll             NSScrollView()                 UIScrollView()    vertical
      7 Divider            NSBox()                        UIView()          the shims' default: branch
      8 Image              ImageView()                    UIImageView()
      9 Toggle             NSSwitch()                     UISwitch()        no label: the caption is a sibling
     10 Spacer             NSView()                       UIView()          grows through Prop.Grow
     11 ProgressBar        NSProgressIndicator()          UIProgressView()
     12 ActivityIndicator  NSProgressIndicator()          UIActivityIndicatorView()  spins while mounted
     13 Slider             NSSlider()                     UISlider()
     14 SecureField        NSSecureTextField()            UITextField()     isSecureTextEntry on UIKit
     15 ScrollHorizontal   NSScrollView()                 UIScrollView()    the axis is read at create
     16 Alert              AlertView()                    AlertView()       a placeholder; NSAlert / UIAlertController at present
     17 Sheet              SheetView()                    SheetView()       a container; a sheet window / a presented controller
     18 Picker             NSPopUpButton()                UIButton()        UIKit: a menu-backed button, not UIPickerView — that is a wheel, wrong for a short list */
sui_handle sui_create(int32_t kind);
void sui_destroy(sui_handle h);

/* --- properties -------------------------------------------------------------- */
void sui_set_text(sui_handle h, const char *text);
void sui_set_placeholder(sui_handle h, const char *text);
void sui_set_checked(sui_handle h, int32_t on);
int32_t sui_get_checked(sui_handle h);
void sui_set_enabled(sui_handle h, int32_t on);
void sui_set_spacing(sui_handle h, int32_t dp);
void sui_set_padding(sui_handle h, int32_t dp);
/* role: 0 Title, 1 Body, 2 Caption */
void sui_set_text_role(sui_handle h, int32_t role);
/* emphasis: 0 Normal, 1 Secondary */
void sui_set_text_emphasis(sui_handle h, int32_t emphasis);
void sui_set_grow(sui_handle h, int32_t on);
/* align: 0 Start, 1 Center, 2 End */
void sui_set_align(sui_handle h, int32_t align);
/* Colour is passed as three components plus a "set" flag rather than a struct:
   `None` means "leave it to the platform", which is not the same as black. */
void sui_set_tint(sui_handle h, int32_t has, int32_t r, int32_t g, int32_t b);
void sui_set_fill(sui_handle h, int32_t has, int32_t r, int32_t g, int32_t b);
void sui_set_image_file(sui_handle h, const char *path);
void sui_set_image_bytes(sui_handle h, const uint8_t *data, int32_t length);
void sui_clear_image(sui_handle h);
/* fit: 0 Contain, 1 Cover, 2 Fill */
void sui_set_content_fit(sui_handle h, int32_t fit);
/* has 0 means indeterminate, which is deliberately not the same as a fraction of 0.0.
   The fraction is 0.0-1.0; the shim scales it for NSProgressIndicator's 0-100. */
void sui_set_progress(sui_handle h, int32_t has, double fraction);
/* A slider's bounds, in the app's own units. Always arrives before sui_set_value. */
void sui_set_range(sui_handle h, double min, double max);
/* A slider's value, in the app's own units. Written only when it differs, so an
   app writing back what the user dragged to does not fight the drag. */
void sui_set_value(sui_handle h, double value);

/* --- events ------------------------------------------------------------------ */
void sui_on_tap(sui_handle h, sui_void_cb cb, int64_t ctx);
void sui_on_text_change(sui_handle h, sui_text_cb cb, int64_t ctx);
void sui_on_checked_change(sui_handle h, sui_bool_cb cb, int64_t ctx);
void sui_on_value_change(sui_handle h, sui_value_cb cb, int64_t ctx);

/* --- tree -------------------------------------------------------------------- */
void sui_insert_after(sui_handle parent, sui_handle child, sui_handle after);
void sui_remove_child(sui_handle parent, sui_handle child);

/* --- layout ------------------------------------------------------------------ */
/* Out-parameters, not a returned NSSize: see the header comment. maxW/maxH are
   NaN for "unconstrained", matching Constraints. */
void sui_measure(sui_handle h, double maxW, double maxH, double *outMinW,
                 double *outMinH, double *outNatW, double *outNatH);
void sui_set_frame(sui_handle h, double x, double y, double w, double height);

/* --- threading --------------------------------------------------------------- */
void sui_run_on_main(sui_void_cb cb, int64_t ctx);
/* The same, after at least `delay_ms`. For waiting on the platform a frame at a time
   rather than spinning the run loop with sui_run_on_main. */
void sui_run_on_main_after(int32_t delay_ms, sui_void_cb cb, int64_t ctx);

/* --- virtual rows ------------------------------------------------------------ */
/* The one place control is inverted: everywhere else Scala builds a tree and the shim
   obeys, but a table asks for the row it is about to show and recycles the ones it is not. */
/* An NSTableView / UITableView inside its scroller. `cb` is called for each row
   that becomes visible, with a recycled view or NULL. */
sui_handle sui_create_table(sui_row_cb cb, int64_t ctx);
/* The new row count, from RowSource.onInvalidate. */
void sui_table_reload(sui_handle h, int32_t count);
/* How many row views the table has actually created. The measurement that says
   virtualisation is working, so it is part of the ABI rather than the self-test. */
int32_t sui_table_materialised(sui_handle h);
/* How many table sources the shim still owns. Falls back to zero once every
   virtual list is destroyed; the measurement that says destroying one frees it. */
int32_t sui_table_live(void);

/* --- presentation ------------------------------------------------------------ */
/* Shows an Alert or a Sheet over the app. Called after its children are mounted. */
void sui_present(sui_handle h);
/* Takes it down because the app asked. Never reported through sui_on_dismiss, which is
   for the platform closing it. Does not release the handle: sui_destroy does. */
void sui_dismiss(sui_handle h);
/* An alert's secondary text. */
void sui_set_message(sui_handle h, const char *text);
void sui_alert_clear_actions(sui_handle h);
/* role: 0 plain, 1 destructive, 2 cancel. Roles, not styling: each platform decides what
   they look like and where they go. */
void sui_alert_add_action(sui_handle h, const char *label, int32_t role,
                          sui_void_cb cb, int64_t ctx);
/* The platform closed it without a choice: Escape, a swipe down. */
void sui_on_dismiss(sui_handle h, sui_void_cb cb, int64_t ctx);

/* --- context menus ----------------------------------------------------------- */
/* Removes the view's menu items. A view with none has no menu. */
void sui_menu_clear(sui_handle h);
/* Appends one item. Order is the order given. */
void sui_menu_add_item(sui_handle h, const char *label, int32_t enabled,
                       sui_void_cb cb, int64_t ctx);

/* --- picker ------------------------------------------------------------------ */
void sui_picker_clear_options(sui_handle h);
void sui_picker_add_option(sui_handle h, const char *label);
/* -1 for no selection. */
void sui_set_selected(sui_handle h, int32_t index);
int32_t sui_get_selected(sui_handle h);
/* The index the user chose. */
void sui_on_select(sui_handle h, sui_int_cb cb, int64_t ctx);

/* --- navigation -------------------------------------------------------------- */
/* Starts describing the stack. Nothing changes on screen until sui_pages_commit. */
void sui_pages_begin(void);
/* The next page up. `id` is stable for as long as the page is on the stack, and so is its
   `content`, which stays mounted while it is covered. */
void sui_pages_add(int64_t id, sui_handle content, const char *title);
/* Makes the platform's stack match what was described. */
void sui_pages_commit(void);
/* The platform popped the stack itself, to the depth given. Never called for a change
   the app made through sui_pages_commit. */
void sui_on_pages_popped(sui_int_cb cb, int64_t ctx);

/* --- inspection, for the self-test ------------------------------------------- */
int32_t sui_child_count(sui_handle h);
sui_handle sui_child_at(sui_handle h, int32_t index);
/* Returns NULL when the view carries no text. The buffer is owned by the shim and
   valid until the next call, so Scala must copy before calling again. */
const char *sui_get_text(sui_handle h);
int32_t sui_is_text_bearing(sui_handle h);
/* The platform class of the view, e.g. NSSwitch. What the platform built, not what
   the renderer asked for. Same buffer rule as sui_get_text. */
const char *sui_class_name(sui_handle h);
/* A determinate fraction 0.0-1.0; -1 when indeterminate (a spinner, or a bar given
   no fraction); -2 when the view shows no progress at all. */
double sui_get_progress(sui_handle h);
/* A slider's value, in the app's own units. */
double sui_get_value(sui_handle h);
/* 1 when the field masks what is typed into it. */
int32_t sui_is_secure(sui_handle h);
/* 1 when an image view holds a decoded image, 0 when it shows nothing, -1 when `h` is not
   an image view. The difference between a picture and an empty frame of the right size. */
int32_t sui_has_image(sui_handle h);
/* How far a vertical scroller's visible area is from the top of its content, in points:
   0 when it shows the top. -1 when `h` is not a scroller. */
double sui_scroll_offset(sui_handle h);
/* 1 while an Alert or Sheet is on screen, as the platform reports it. */
int32_t sui_is_presented(sui_handle h);
/* The title the platform is *showing* for a presented widget, read from the alert or the
   sheet's own chrome rather than from what the renderer was told. NULL when not presented. */
const char *sui_presented_title(sui_handle h);
/* An alert's secondary text, as shown. */
const char *sui_presented_message(sui_handle h);
/* How many items the platform's menu for this view holds; 0 when it has none. */
int32_t sui_menu_item_count(sui_handle h);
const char *sui_menu_item_label(sui_handle h, int32_t index);
/* How many pages the platform's own stack holds. */
int32_t sui_pages_depth(void);
/* The title the platform shows for page `index`, bottom first: the navigation item's
   on iOS, the sidebar entry's on macOS. */
const char *sui_page_title(int32_t index);
/* The index of the page on screen, bottom first. */
int32_t sui_pages_shown(void);
/* 1 when the platform's own chrome offers going back: a back button, or a sidebar to choose from. */
int32_t sui_pages_back_offered(void);
/* Goes back one page through the platform's own path — popping the navigation controller,
   selecting the previous sidebar entry — exactly as a user would. */
int32_t sui_pages_back(void);
/* How many menu items the shim still holds, counted as they are freed. Falls by a
   row's items when the row is destroyed, or the menu leaked with its view. */
int32_t sui_menu_live(void);
/* Chooses item `index` through the platform's own menu path. 0 where the platform offers
   no way to do that from code (UIKit), rather than a simulation that would pass. */
int32_t sui_menu_activate(sui_handle h, int32_t index);
/* How many things the platform has presented over the app right now — sheets attached to
   the window, or the chain of presented view controllers. The platform's answer, so a
   widget the renderer believes it dismissed but UIKit is still showing counts. */
int32_t sui_presented_count(void);
int32_t sui_alert_action_count(sui_handle h);
/* In the order the platform holds them, which need not be the order declared. */
const char *sui_alert_action_label(sui_handle h, int32_t index);
/* Clicks a button the way a user would, through the control's own action. 0 if not a button. */
int32_t sui_perform_click(sui_handle h);
/* Chooses action `index` through the platform's own response path. 0 where the platform
   offers no way to do that from code (UIKit), rather than a simulation that would pass. */
int32_t sui_alert_choose(sui_handle h, int32_t index);

#endif
