import scala.scalanative.build.*
import scala.sys.process.*

ThisBuild / scalaVersion := "3.9.0"
ThisBuild / organization := "dev.scalaui"
ThisBuild / version      := "0.0.0-S3"

lazy val simSdk = Seq("xcrun", "--sdk", "iphonesimulator", "--show-sdk-path").!!.trim
lazy val triple = "arm64-apple-ios17.0-simulator"

/** S1 finding, mandatory on every iOS target: an iOS triple gives `target.os == "ios"`,
  * javalib's `LinktimeInfo.isMac` only accepts "darwin"/"macosx", and `PosixThread` then
  * calls `pthread_condattr_setclock`, which no Apple platform has. Without this override
  * nothing touching `java.lang.Thread` links — and S3 uses a background thread.
  */
lazy val appleOsOverride = Map("scala.scalanative.meta.linktimeinfo.target.os" -> "darwin")

lazy val scalaLib = Project("scalaLib", file("target-builds/simArm64"))
  .enablePlugins(ScalaNativePlugin)
  .settings(
    name                  := "s3-scala-lib",
    Compile / scalaSource := (ThisBuild / baseDirectory).value / "scala-lib" / "src" / "main" / "scala",
    scalacOptions ++= Seq("-deprecation", "-feature", "-unchecked", "-source:3.9", "-no-indent"),
    // Bindings are generated by ./regen-bindings.sh and checked in, not produced here:
    // sn-bindgen 0.4.5's macOS binary needs a libclang that Homebrew only ships as
    // llvm@17. See that script for the reasoning.
    nativeConfig := {
      val c     = nativeConfig.value
      val flags = Seq("-target", triple, "-isysroot", simSdk)
      c.withBuildTarget(BuildTarget.libraryStatic)
        .withGC(GC.immix) // the only GC that builds for iOS (S1)
        .withMode(Mode.debug)
        .withLTO(LTO.none)
        .withTargetTriple(triple)
        // -target/-isysroot must reach clang for Scala Native's own bundled C sources too.
        .withCompileOptions(c.compileOptions ++ flags ++
          Seq("-I" + ((ThisBuild / baseDirectory).value / "shim" / "include").toString))
        .withLinkingOptions(c.linkingOptions ++ flags)
        .withLinktimeProperties(c.linktimeProperties ++ appleOsOverride)
    }
  )

lazy val root = project.in(file(".")).aggregate(scalaLib).settings(publish / skip := true)
