addSbtPlugin("org.scala-native" % "sbt-scala-native" % "0.5.12")
// No bindgen plugin: bindings are generated by ./regen-bindings.sh and checked in, because
// sn-bindgen 0.4.5's macOS binary needs a libclang Homebrew only ships as llvm@17.
