package thicket.tools.shim

import thicket.tools.shim.Abi.{CType, Fn, Group, Param}

/** Emits the declaration layer of the Apple shim from [[Abi]].
  *
  * Three of the four declarations per function are mechanical and are emitted here: the C header, the Scala `@extern`
  * bindings, and the Swift `@_cdecl` signature. The fourth — the Swift function *body* — is not, and
  * [[swiftSignatures]] deliberately emits signatures with a `fatalError` placeholder rather than a guess: measured on
  * the two shims that exist, only 7 of 34 bodies are byte-identical across AppKit and UIKit, and the rest are real
  * platform differences (`placeholderString` vs `placeholder`, `imageScaling` vs `contentMode`).
  *
  * So this is a scaffolding and consistency tool, not a code-writing one. That is the honest scope, and it is the scope
  * that removes the failure that actually hurts: a silent disagreement between the three declarations.
  */
object Emit {

  // -- C header ------------------------------------------------------------

  private def cType(t: CType): String =
    t match {
      case CType.Void    => "void"
      case CType.I32     => "int32_t"
      case CType.I64     => "int64_t"
      case CType.F64     => "double"
      case CType.Str     => "const char *"
      case CType.Bytes   => "const uint8_t *"
      case CType.OutF64  => "double *"
      case CType.Handle  => "sui_handle"
      case CType.VoidCb  => "sui_void_cb"
      case CType.TextCb  => "sui_text_cb"
      case CType.BoolCb  => "sui_bool_cb"
      case CType.RowCb   => "sui_row_cb"
      case CType.ValueCb => "sui_value_cb"
    }

  private def cParam(p: Param): String = {
    val t = cType(p.tpe)
    if t.endsWith("*") then s"$t${p.name}" else s"$t ${p.name}"
  }

  private def cDecl(fn: Fn): String = {
    val ret = cType(fn.ret)
    val args = if fn.params.isEmpty then "void" else fn.params.map(cParam).mkString(", ")
    val head = if ret.endsWith("*") then s"$ret${fn.name}" else s"$ret ${fn.name}"
    val one = s"$head($args);"
    if one.length <= 100 then one
    else {
      // Wrap on the argument list, aligned under the open paren, the way the hand-written
      // header does it.
      val indent = " " * (head.length + 1)
      val (first, rest) = fn.params.map(cParam).splitAt(fn.params.length / 2 + 1)
      s"$head(${first.mkString(", ")},\n$indent${rest.mkString(", ")});"
    }
  }

  def cHeader(groups: List[Group] = Abi.groups): String = {
    val sb = new StringBuilder
    sb.append("""/*
 * The Scala <-> Apple contract.
 *
 * GENERATED by tools/shim-gen from thicket.tools.shim.Abi. Do not edit by hand: edit
 * tools/shim-gen/src/main/scala/thicket/tools/shim/Abi.scala and run `sbt shimGen/run`.
 * `sbt shimGen/test` fails while this file and Abi disagree, because otherwise the Scala
 * bindings and the two Swift shims drift from it and nothing says so until a callback
 * reads the wrong register.
 *
 * NO STRUCTS BY VALUE anywhere a Scala callback is involved, and none returned across the
 * boundary either: S4 found Scala Native returns a small struct from a CFuncPtr in the
 * wrong registers, silently, and S3 confirmed it still does on arm64 with a *different*
 * wrong answer. NSRect/NSSize are pervasive in AppKit, so everything here is flattened to
 * scalars or out-parameters.
 */
#ifndef THICKET_APPLE_H
#define THICKET_APPLE_H

#include <stdint.h>

#include "thicket_apple_types.h"
""")
    groups.foreach { g =>
      val bar = "-" * math.max(3, 78 - g.title.length - 6)
      sb.append(s"\n/* --- ${g.title} $bar */\n")
      if g.doc.nonEmpty then sb.append(s"/* ${g.doc} */\n")
      g.fns.foreach { fn =>
        if fn.doc.nonEmpty then sb.append(s"/* ${fn.doc} */\n")
        sb.append(cDecl(fn)).append("\n")
      }
    }
    sb.append("\n#endif\n")
    sb.toString
  }

  // -- Scala @extern -------------------------------------------------------

  private def scalaType(t: CType): String =
    t match {
      case CType.Void => "Unit"
      case CType.I32  => "CInt"
      case CType.I64  => "Long"
      case CType.F64  => "CDouble"
      case CType.Str  => "CString"
      // Not Ptr[UByte]: the renderer fills the buffer with `alloc[Byte]`, and the two are the
      // same register at the ABI (see Abi.Repr).
      case CType.Bytes   => "Ptr[Byte]"
      case CType.OutF64  => "Ptr[CDouble]"
      case CType.Handle  => "Handle"
      case CType.VoidCb  => "VoidCb"
      case CType.TextCb  => "TextCb"
      case CType.BoolCb  => "BoolCb"
      case CType.RowCb   => "RowCb"
      case CType.ValueCb => "ValueCb"
    }

  /** The generated Scala file: the `@extern` bindings, then the kind codes.
    *
    * The codes live in their own object because an `@extern` object may contain nothing but externs and type aliases.
    * `inline val`, so a code is a literal at the call site exactly as the hand-written numbers were.
    */
  def scalaExterns(
    fns:   List[Fn] = Abi.all,
    kinds: List[Abi.Kind] = Abi.kinds
  ): String = {
    val sb = new StringBuilder
    sb.append("""package thicket.renderer.apple

import scala.scalanative.unsafe.*

/** Bindings for `shim/include/thicket_apple.h`.
  *
  * GENERATED by tools/shim-gen from thicket.tools.shim.Abi. Do not edit by hand: edit
  * Abi.scala and run `sbt shimGen/run`. `sbt shimGen/test` fails while this file and Abi
  * disagree.
  *
  * Every signature is scalars or out-parameters: no struct crosses this boundary by value,
  * because Scala Native gets that silently wrong on both x86-64 and arm64 (S4, S3).
  */
@extern
object Shim {

  type Handle = Ptr[Byte]
  type VoidCb = CFuncPtr1[Long, Unit]
  type TextCb = CFuncPtr2[Long, CString, Unit]
  type BoolCb = CFuncPtr2[Long, CInt, Unit]

  /** The only callback that returns a value. A returned pointer is one register; what S4 and S3 found silently broken
    * was a returned small struct.
    */
  type RowCb = CFuncPtr3[Long, CInt, Handle, Handle]

  /** A slider's value, in the app's own units. */
  type ValueCb = CFuncPtr2[Long, Double, Unit]

""")
    fns.foreach { fn =>
      val args = fn.params.map(p => s"${p.name}: ${scalaType(p.tpe)}").mkString(", ")
      sb.append(s"  def ${fn.name}($args): ${scalaType(fn.ret)} = extern\n")
    }
    sb.append("}\n")
    sb.append("""
/** `sui_create` kind codes, from Abi.kinds. A code whose view is "-" on a toolkit is
  * reserved and not built there; see the table in `thicket_apple.h`.
  */
object ShimKind {
""")
    kinds.foreach { k =>
      sb.append(s"  inline val ${k.name} = ${k.code}\n")
    }
    sb.append("}\n")
    sb.toString
  }

  // -- Swift signatures ----------------------------------------------------

  private def swiftType(t: CType): String =
    t match {
      case CType.I32     => "Int32"
      case CType.I64     => "Int64"
      case CType.F64     => "Double"
      case CType.Str     => "UnsafePointer<CChar>"
      case CType.Bytes   => "UnsafePointer<UInt8>"
      case CType.OutF64  => "UnsafeMutablePointer<Double>"
      case CType.Handle  => "UnsafeMutableRawPointer"
      case CType.VoidCb  => "@escaping sui_void_cb"
      case CType.TextCb  => "@escaping sui_text_cb"
      case CType.BoolCb  => "@escaping sui_bool_cb"
      case CType.RowCb   => "@escaping sui_row_cb"
      case CType.ValueCb => "@escaping sui_value_cb"
      case CType.Void    => "Void"
    }

  /** Swift `@_cdecl` signatures with placeholder bodies.
    *
    * For scaffolding a new shim, and for checking an existing one. The body is `fatalError`, never a guess: see the
    * object comment.
    */
  def swiftSignatures(fns: List[Fn] = Abi.all): String = {
    val sb = new StringBuilder
    sb.append("""// GENERATED signatures — bodies are NOT generated and must be written by hand.
// See tools/shim-gen and docs/13-phases.md §13.3.

""")
    fns.foreach { fn =>
      val args = fn.params.map(p => s"_ ${p.name}: ${swiftType(p.tpe)}").mkString(", ")
      val ret = if fn.ret == CType.Void then "" else s" -> ${swiftType(fn.ret)}"
      sb.append(s"""@_cdecl("${fn.name}")\n""")
      sb.append(s"public func ${fn.name}($args)$ret {\n")
      sb.append(s"""  fatalError("${fn.name} is not implemented in this shim")\n""")
      sb.append("}\n\n")
    }
    sb.toString
  }

}
